#!/usr/bin/env python3

"""
Script used to run the webservice locally.
"""

from argparse import ArgumentParser

from clickandobey.dockerized.webservice.api.app import API


def __parse_args():
    parser = ArgumentParser()

    parser.add_argument("--debug", action="store_true", help="Run the application in debug mode.")

    return parser.parse_args()


def main():
    """
    Main method used to start the webservice.
    """
    args = __parse_args()
    API.run(host="0.0.0.0", port="9001", debug=args.debug)


if __name__ == "__main__":
    main()
