name: Python Dockerized Webservice CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lintMarkdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Markdown
      run: |
        make lint-markdown
  lintPython:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Python
      run: |
        make lint-python
  unitTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Unit Test
      run: |
        make unit-test-docker FAIL_FAST=TRUE
  integrationTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Integration Test
      run: |
        make integration-test-docker FAIL_FAST=TRUE
